package com.hzit.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Car {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_Id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.series_Id
     *
     * @mbggenerated
     */
    private Integer seriesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_Name
     *
     * @mbggenerated
     */
    private String carName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_Price
     *
     * @mbggenerated
     */
    private BigDecimal carPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_Time
     *
     * @mbggenerated
     */
    private Date carTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_Id
     *
     * @return the value of car.car_Id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_Id
     *
     * @param carId the value for car.car_Id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.series_Id
     *
     * @return the value of car.series_Id
     *
     * @mbggenerated
     */
    public Integer getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.series_Id
     *
     * @param seriesId the value for car.series_Id
     *
     * @mbggenerated
     */
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_Name
     *
     * @return the value of car.car_Name
     *
     * @mbggenerated
     */
    public String getCarName() {
        return carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_Name
     *
     * @param carName the value for car.car_Name
     *
     * @mbggenerated
     */
    public void setCarName(String carName) {
        this.carName = carName == null ? null : carName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_Price
     *
     * @return the value of car.car_Price
     *
     * @mbggenerated
     */
    public BigDecimal getCarPrice() {
        return carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_Price
     *
     * @param carPrice the value for car.car_Price
     *
     * @mbggenerated
     */
    public void setCarPrice(BigDecimal carPrice) {
        this.carPrice = carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_Time
     *
     * @return the value of car.car_Time
     *
     * @mbggenerated
     */
    public Date getCarTime() {
        return carTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_Time
     *
     * @param carTime the value for car.car_Time
     *
     * @mbggenerated
     */
    public void setCarTime(Date carTime) {
        this.carTime = carTime;
    }

    @Override
    public String toString() {
        return "Car{" +
                "carId=" + carId +
                ", seriesId=" + seriesId +
                ", carName='" + carName + '\'' +
                ", carPrice=" + carPrice +
                ", carTime=" + carTime +
                '}';
    }
}