package com.hzit.bean;

import java.util.List;

public class CarBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.brand_Id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.brand_Name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.brand_Num
     *
     * @mbggenerated
     */
    private String brandNum;

    private List<CarSeries> carSeriesList;

    public List<CarSeries> getCarSeriesList() {
        return carSeriesList;
    }

    public void setCarSeriesList(List<CarSeries> carSeriesList) {
        this.carSeriesList = carSeriesList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.brand_Id
     *
     * @return the value of carbrand.brand_Id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.brand_Id
     *
     * @param brandId the value for carbrand.brand_Id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.brand_Name
     *
     * @return the value of carbrand.brand_Name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.brand_Name
     *
     * @param brandName the value for carbrand.brand_Name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.brand_Num
     *
     * @return the value of carbrand.brand_Num
     *
     * @mbggenerated
     */
    public String getBrandNum() {
        return brandNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.brand_Num
     *
     * @param brandNum the value for carbrand.brand_Num
     *
     * @mbggenerated
     */
    public void setBrandNum(String brandNum) {
        this.brandNum = brandNum == null ? null : brandNum.trim();
    }

    @Override
    public String toString() {
        return "CarBrand{" +
                "brandId=" + brandId +
                ", brandName='" + brandName + '\'' +
                ", brandNum='" + brandNum + '\'' +
                '}';
    }
}