package com.hzit.bean;

import java.math.BigDecimal;

public class CarOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carorder.order_Id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carorder.car_Id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carorder.company_Id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carorder.order_Num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carorder.order_Type
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carorder.order_Total_Price
     *
     * @mbggenerated
     */
    private BigDecimal orderTotalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carorder.order_Id
     *
     * @return the value of carorder.order_Id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carorder.order_Id
     *
     * @param orderId the value for carorder.order_Id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carorder.car_Id
     *
     * @return the value of carorder.car_Id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carorder.car_Id
     *
     * @param carId the value for carorder.car_Id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carorder.company_Id
     *
     * @return the value of carorder.company_Id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carorder.company_Id
     *
     * @param companyId the value for carorder.company_Id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carorder.order_Num
     *
     * @return the value of carorder.order_Num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carorder.order_Num
     *
     * @param orderNum the value for carorder.order_Num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carorder.order_Type
     *
     * @return the value of carorder.order_Type
     *
     * @mbggenerated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carorder.order_Type
     *
     * @param orderType the value for carorder.order_Type
     *
     * @mbggenerated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carorder.order_Total_Price
     *
     * @return the value of carorder.order_Total_Price
     *
     * @mbggenerated
     */
    public BigDecimal getOrderTotalPrice() {
        return orderTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carorder.order_Total_Price
     *
     * @param orderTotalPrice the value for carorder.order_Total_Price
     *
     * @mbggenerated
     */
    public void setOrderTotalPrice(BigDecimal orderTotalPrice) {
        this.orderTotalPrice = orderTotalPrice;
    }
}