package com.hzit.bean;

public class CarSeries {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.series_Id
     *
     * @mbggenerated
     */
    private Integer seriesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.brand_Id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.series_Name
     *
     * @mbggenerated
     */
    private String seriesName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.series_Id
     *
     * @return the value of carseries.series_Id
     *
     * @mbggenerated
     */
    public Integer getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.series_Id
     *
     * @param seriesId the value for carseries.series_Id
     *
     * @mbggenerated
     */
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.brand_Id
     *
     * @return the value of carseries.brand_Id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.brand_Id
     *
     * @param brandId the value for carseries.brand_Id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.series_Name
     *
     * @return the value of carseries.series_Name
     *
     * @mbggenerated
     */
    public String getSeriesName() {
        return seriesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.series_Name
     *
     * @param seriesName the value for carseries.series_Name
     *
     * @mbggenerated
     */
    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName == null ? null : seriesName.trim();
    }
}