package com.hzit.bean;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_Id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.company_Id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_Name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_Phone
     *
     * @mbggenerated
     */
    private String customerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_Sex
     *
     * @mbggenerated
     */
    private String customerSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_Type
     *
     * @mbggenerated
     */
    private String customerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_Birthday
     *
     * @mbggenerated
     */
    private Date customerBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_Create_Time
     *
     * @mbggenerated
     */
    private Date customerCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_Id
     *
     * @return the value of customer.customer_Id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_Id
     *
     * @param customerId the value for customer.customer_Id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.company_Id
     *
     * @return the value of customer.company_Id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.company_Id
     *
     * @param companyId the value for customer.company_Id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_Name
     *
     * @return the value of customer.customer_Name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_Name
     *
     * @param customerName the value for customer.customer_Name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_Phone
     *
     * @return the value of customer.customer_Phone
     *
     * @mbggenerated
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_Phone
     *
     * @param customerPhone the value for customer.customer_Phone
     *
     * @mbggenerated
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_Sex
     *
     * @return the value of customer.customer_Sex
     *
     * @mbggenerated
     */
    public String getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_Sex
     *
     * @param customerSex the value for customer.customer_Sex
     *
     * @mbggenerated
     */
    public void setCustomerSex(String customerSex) {
        this.customerSex = customerSex == null ? null : customerSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_Type
     *
     * @return the value of customer.customer_Type
     *
     * @mbggenerated
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_Type
     *
     * @param customerType the value for customer.customer_Type
     *
     * @mbggenerated
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_Birthday
     *
     * @return the value of customer.customer_Birthday
     *
     * @mbggenerated
     */
    public Date getCustomerBirthday() {
        return customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_Birthday
     *
     * @param customerBirthday the value for customer.customer_Birthday
     *
     * @mbggenerated
     */
    public void setCustomerBirthday(Date customerBirthday) {
        this.customerBirthday = customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_Create_Time
     *
     * @return the value of customer.customer_Create_Time
     *
     * @mbggenerated
     */
    public Date getCustomerCreateTime() {
        return customerCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_Create_Time
     *
     * @param customerCreateTime the value for customer.customer_Create_Time
     *
     * @mbggenerated
     */
    public void setCustomerCreateTime(Date customerCreateTime) {
        this.customerCreateTime = customerCreateTime;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "customerId=" + customerId +
                ", companyId=" + companyId +
                ", customerName='" + customerName + '\'' +
                ", customerPhone='" + customerPhone + '\'' +
                ", customerSex='" + customerSex + '\'' +
                ", customerType='" + customerType + '\'' +
                ", customerBirthday=" + customerBirthday +
                ", customerCreateTime=" + customerCreateTime +
                '}';
    }
}