package com.hzit.bean;

import java.math.BigDecimal;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_Id
     *
     * @mbggenerated
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.position_Id
     *
     * @mbggenerated
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.company_Id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_Name
     *
     * @mbggenerated
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_Phone
     *
     * @mbggenerated
     */
    private String empPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_Password
     *
     * @mbggenerated
     */
    private String empPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_Salery
     *
     * @mbggenerated
     */
    private BigDecimal empSalery;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_Id
     *
     * @return the value of employee.emp_Id
     *
     * @mbggenerated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_Id
     *
     * @param empId the value for employee.emp_Id
     *
     * @mbggenerated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.position_Id
     *
     * @return the value of employee.position_Id
     *
     * @mbggenerated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.position_Id
     *
     * @param positionId the value for employee.position_Id
     *
     * @mbggenerated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.company_Id
     *
     * @return the value of employee.company_Id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.company_Id
     *
     * @param companyId the value for employee.company_Id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_Name
     *
     * @return the value of employee.emp_Name
     *
     * @mbggenerated
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_Name
     *
     * @param empName the value for employee.emp_Name
     *
     * @mbggenerated
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_Phone
     *
     * @return the value of employee.emp_Phone
     *
     * @mbggenerated
     */
    public String getEmpPhone() {
        return empPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_Phone
     *
     * @param empPhone the value for employee.emp_Phone
     *
     * @mbggenerated
     */
    public void setEmpPhone(String empPhone) {
        this.empPhone = empPhone == null ? null : empPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_Password
     *
     * @return the value of employee.emp_Password
     *
     * @mbggenerated
     */
    public String getEmpPassword() {
        return empPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_Password
     *
     * @param empPassword the value for employee.emp_Password
     *
     * @mbggenerated
     */
    public void setEmpPassword(String empPassword) {
        this.empPassword = empPassword == null ? null : empPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_Salery
     *
     * @return the value of employee.emp_Salery
     *
     * @mbggenerated
     */
    public BigDecimal getEmpSalery() {
        return empSalery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_Salery
     *
     * @param empSalery the value for employee.emp_Salery
     *
     * @mbggenerated
     */
    public void setEmpSalery(BigDecimal empSalery) {
        this.empSalery = empSalery;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "empId=" + empId +
                ", positionId=" + positionId +
                ", companyId=" + companyId +
                ", empName='" + empName + '\'' +
                ", empPhone='" + empPhone + '\'' +
                ", empPassword='" + empPassword + '\'' +
                ", empSalery=" + empSalery +
                '}';
    }
}