package com.hzit.bean;

public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_Id
     *
     * @mbggenerated
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_Name
     *
     * @mbggenerated
     */
    private String positionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_Level
     *
     * @mbggenerated
     */
    private String positionLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_Id
     *
     * @return the value of position.position_Id
     *
     * @mbggenerated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_Id
     *
     * @param positionId the value for position.position_Id
     *
     * @mbggenerated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_Name
     *
     * @return the value of position.position_Name
     *
     * @mbggenerated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_Name
     *
     * @param positionName the value for position.position_Name
     *
     * @mbggenerated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_Level
     *
     * @return the value of position.position_Level
     *
     * @mbggenerated
     */
    public String getPositionLevel() {
        return positionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_Level
     *
     * @param positionLevel the value for position.position_Level
     *
     * @mbggenerated
     */
    public void setPositionLevel(String positionLevel) {
        this.positionLevel = positionLevel == null ? null : positionLevel.trim();
    }
}