package com.hzit.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Repertory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.repertory_Id
     *
     * @mbggenerated
     */
    private Integer repertoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.car_Id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.company_Id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.purchase_Price
     *
     * @mbggenerated
     */
    private BigDecimal purchasePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.in_Time
     *
     * @mbggenerated
     */
    private Date inTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.repertory_Num
     *
     * @mbggenerated
     */
    private Integer repertoryNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.repertory_Id
     *
     * @return the value of repertory.repertory_Id
     *
     * @mbggenerated
     */
    public Integer getRepertoryId() {
        return repertoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repertory.repertory_Id
     *
     * @param repertoryId the value for repertory.repertory_Id
     *
     * @mbggenerated
     */
    public void setRepertoryId(Integer repertoryId) {
        this.repertoryId = repertoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.car_Id
     *
     * @return the value of repertory.car_Id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repertory.car_Id
     *
     * @param carId the value for repertory.car_Id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.company_Id
     *
     * @return the value of repertory.company_Id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repertory.company_Id
     *
     * @param companyId the value for repertory.company_Id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.purchase_Price
     *
     * @return the value of repertory.purchase_Price
     *
     * @mbggenerated
     */
    public BigDecimal getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repertory.purchase_Price
     *
     * @param purchasePrice the value for repertory.purchase_Price
     *
     * @mbggenerated
     */
    public void setPurchasePrice(BigDecimal purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.in_Time
     *
     * @return the value of repertory.in_Time
     *
     * @mbggenerated
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repertory.in_Time
     *
     * @param inTime the value for repertory.in_Time
     *
     * @mbggenerated
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.repertory_Num
     *
     * @return the value of repertory.repertory_Num
     *
     * @mbggenerated
     */
    public Integer getRepertoryNum() {
        return repertoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repertory.repertory_Num
     *
     * @param repertoryNum the value for repertory.repertory_Num
     *
     * @mbggenerated
     */
    public void setRepertoryNum(Integer repertoryNum) {
        this.repertoryNum = repertoryNum;
    }
}