package com.hzit.bean;

import com.hzit.util.MyConst;

import java.math.BigDecimal;
import java.util.Date;

public class Sale {
    private Integer saleId;
    private Integer customerId;
    private Integer carId;
    private Integer empId;
    private Integer companyId;
    private BigDecimal saleCurprice;
    private Integer saleNum;
    private String saleType;
    private BigDecimal saleTotalprice;
    private Date saleTime;
    private Employee employee;
    private Customer customer;
    private Car car;

    public String getSaleTypeFormat() {
        String str = null;
        if (MyConst.NOTPAYING.equals(saleType)){
            str = "未付款";
        } else if (MyConst.HASPAYING.equals(saleType)){
            str = "已付款";
        }
        return str;
    }
    @Override
    public String toString() {
        return "Sale{" +
                "saleId=" + saleId +
                ", customerId=" + customerId +
                ", carId=" + carId +
                ", empId=" + empId +
                ", companyId=" + companyId +
                ", saleCurprice=" + saleCurprice +
                ", saleNum=" + saleNum +
                ", saleType='" + saleType + '\'' +
                ", saleTotalprice=" + saleTotalprice +
                ", saleTime=" + saleTime +
                ", employee=" + employee +
                ", customer=" + customer +
                ", car=" + car +
                '}';
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Car getCar() {
        return car;
    }

    public void setCar(Car car) {
        this.car = car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.sale_Id
     *
     * @return the value of Sale.sale_Id
     *
     * @mbggenerated
     */
    public Integer getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.sale_Id
     *
     * @param saleId the value for Sale.sale_Id
     *
     * @mbggenerated
     */
    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.customer_Id
     *
     * @return the value of Sale.customer_Id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.customer_Id
     *
     * @param customerId the value for Sale.customer_Id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.car_Id
     *
     * @return the value of Sale.car_Id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.car_Id
     *
     * @param carId the value for Sale.car_Id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.emp_Id
     *
     * @return the value of Sale.emp_Id
     *
     * @mbggenerated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.emp_Id
     *
     * @param empId the value for Sale.emp_Id
     *
     * @mbggenerated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.company_Id
     *
     * @return the value of Sale.company_Id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.company_Id
     *
     * @param companyId the value for Sale.company_Id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.sale_CurPrice
     *
     * @return the value of Sale.sale_CurPrice
     *
     * @mbggenerated
     */
    public BigDecimal getSaleCurprice() {
        return saleCurprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.sale_CurPrice
     *
     * @param saleCurprice the value for Sale.sale_CurPrice
     *
     * @mbggenerated
     */
    public void setSaleCurprice(BigDecimal saleCurprice) {
        this.saleCurprice = saleCurprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.sale_Num
     *
     * @return the value of Sale.sale_Num
     *
     * @mbggenerated
     */
    public Integer getSaleNum() {
        return saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.sale_Num
     *
     * @param saleNum the value for Sale.sale_Num
     *
     * @mbggenerated
     */
    public void setSaleNum(Integer saleNum) {
        this.saleNum = saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.sale_Type
     *
     * @return the value of Sale.sale_Type
     *
     * @mbggenerated
     */
    public String getSaleType() {
        return saleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.sale_Type
     *
     * @param saleType the value for Sale.sale_Type
     *
     * @mbggenerated
     */
    public void setSaleType(String saleType) {
        this.saleType = saleType == null ? null : saleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.sale_TotalPrice
     *
     * @return the value of Sale.sale_TotalPrice
     *
     * @mbggenerated
     */
    public BigDecimal getSaleTotalprice() {
        return saleTotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.sale_TotalPrice
     *
     * @param saleTotalprice the value for Sale.sale_TotalPrice
     *
     * @mbggenerated
     */
    public void setSaleTotalprice(BigDecimal saleTotalprice) {
        this.saleTotalprice = saleTotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sale.sale_Time
     *
     * @return the value of Sale.sale_Time
     *
     * @mbggenerated
     */
    public Date getSaleTime() {
        return saleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sale.sale_Time
     *
     * @param saleTime the value for Sale.sale_Time
     *
     * @mbggenerated
     */
    public void setSaleTime(Date saleTime) {
        this.saleTime = saleTime;
    }
}