package com.hzit.mapper;

import com.hzit.bean.AdminLog;

public interface AdminLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbggenerated
     */
    int insert(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbggenerated
     */
    int insertSelective(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbggenerated
     */
    AdminLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminLog record);
}