package com.hzit.mapper;

import com.hzit.bean.CarBrand;

import java.util.List;

public interface CarBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carbrand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carbrand
     *
     * @mbggenerated
     */
    int insert(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carbrand
     *
     * @mbggenerated
     */
    int insertSelective(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carbrand
     *
     * @mbggenerated
     */
    CarBrand selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carbrand
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carbrand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarBrand record);

    List<CarBrand> selectAllBand();

    CarBrand selectById(Integer brandId);


}