package com.hzit.mapper;

import com.hzit.bean.CarSeries;

public interface CarSeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer seriesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbggenerated
     */
    int insert(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbggenerated
     */
    int insertSelective(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbggenerated
     */
    CarSeries selectByPrimaryKey(Integer seriesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarSeries record);
}