package com.hzit.mapper;

import com.hzit.bean.Financing;

public interface FinancingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financing
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer financingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financing
     *
     * @mbggenerated
     */
    int insert(Financing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financing
     *
     * @mbggenerated
     */
    int insertSelective(Financing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financing
     *
     * @mbggenerated
     */
    Financing selectByPrimaryKey(Integer financingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financing
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Financing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financing
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Financing record);
}