package com.hzit.mapper;

import com.hzit.bean.Repertory;

public interface RepertoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repertory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer repertoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repertory
     *
     * @mbggenerated
     */
    int insert(Repertory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repertory
     *
     * @mbggenerated
     */
    int insertSelective(Repertory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repertory
     *
     * @mbggenerated
     */
    Repertory selectByPrimaryKey(Integer repertoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repertory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Repertory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repertory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Repertory record);
}