package com.hzit.mapper;

import com.hzit.bean.Sale;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sale
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sale
     *
     * @mbggenerated
     */
    int insert(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sale
     *
     * @mbggenerated
     */
    int insertSelective(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sale
     *
     * @mbggenerated
     */
    Sale selectByPrimaryKey(Integer saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sale
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sale
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sale record);

    List<Sale> selectByCompanyId(@Param(value = "companyId") Integer companyId);
}